name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run build-archiver
        uses: UltimateHackingKeyboard/build-archiver@v0.0.2
        with:
          FILE_PATTERN: "data/*.txt"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S3_ACCESS_KEY: ${{ secrets.UHK_BUILD_ARCHIVER_AWS_ACCESS_SECRET }}
          S3_ACCESS_KEY_ID: ${{ secrets.UHK_BUILD_ARCHIVER_AWS_ACCESS_KEY }}
          S3_BUCKET: "uhk-build-archives"
          S3_KEY_PREFIX: "build-archiver-test/"
          S3_REGION: "eu-central-1"

