name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run build-archiver
        uses: UltimateHackingKeyboard/build-archiver@master
        with:
          FILE_PATTERN: "data/*.txt"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_KEY_PREFIX: "build-archiver-test"
          S3_REGION: "eu-central-1"

